require: rubocop-rspec

# Commonly used screens these days easily fit more than 80 characters.
Layout/LineLength:
  Max: 120

Layout/IndentationWidth:
  # Number of spaces for each indentation level.
  Width: 2