require 'active_support/core_ext/module/delegation'
require 'active_support/core_ext/class/attribute'
require 'active_support/core_ext/string/inflections'
require 'active_support/core_ext/hash'
require 'savon'
require 'nokogiri'
require 'autotask_ruby/client'
require 'autotask_ruby/resource'